### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by anweiss** [stkb/vscode-rewrap#16]
This doesn't seem to work with multiline YAML strings.

vscode v1.7.1
vscode-rewrap v0.6.3

**Comment by stkb** [comment]
Yeah while comments do work in YAML files, other text won't always. You mean like this?

``` yaml
intro: >
    It was the best of times, it was the worst of times, it was the age of wisdom, it was the age
    of foolishness...

      vv into vv

intro: >
    It was the best of times, it was the worst of times, it
    was the age of wisdom, it was the age of foolishness...
```

It doesn't work at the moment because it falls back on the basic paragraph detection, which needs blank lines to separate paragraphs. As a workaround, you can put a blank line between the key and the multiline string to get the wrapping to work, and remove it afterwards.

I think I can add a change that would mark paragraphs by differences in indent, just not sure if that would break anything else.

Also if you'd find it useful, I could look into adding full YAML support. That would mean being able to process a whole document at once. It could also convert into multiline strings where appropriate, eg:

``` yaml
some_text: Some really long text that is much too long to fit on one line.

some_text: >
    Some really long text that is 
    much too long to fit on one line.
````
